In [2]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

In [5]:
#Sample documents

documents = [



"This is a list which containig sample documents.",

"Keywords are important for keyword-based search.",

"Document analysis involves extracting keywords.",

"Keyword-based search relies on sparse embeddings."
]

In [7]:
import re

def preprocess_text(text):

  text =text.lower()
  text =re.sub(r' [^\w\s]', '', text)

  return text

In [8]:
preprocess_documents = [preprocess_text(doc) for doc in documents]

In [10]:
preprocess_documents

['this is a list which containig sample documents.',
 'keywords are important for keyword-based search.',
 'document analysis involves extracting keywords.',
 'keyword-based search relies on sparse embeddings.']

In [11]:
preprocessed_query = preprocess_text("Keyword-based search")

In [12]:
preprocessed_query

'keyword-based search'

In [13]:
vector = TfidfVectorizer()

In [14]:
X = vector.fit_transform(preprocess_documents)

In [15]:
X.toarray()

array([[0.        , 0.        , 0.        , 0.37796447, 0.        ,
        0.37796447, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.37796447, 0.        , 0.        , 0.37796447,
        0.        , 0.        , 0.37796447, 0.        , 0.        ,
        0.37796447, 0.37796447],
       [0.        , 0.42693074, 0.3365971 , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.42693074, 0.42693074,
        0.        , 0.        , 0.3365971 , 0.3365971 , 0.        ,
        0.        , 0.        , 0.        , 0.3365971 , 0.        ,
        0.        , 0.        ],
       [0.46516193, 0.        , 0.        , 0.        , 0.46516193,
        0.        , 0.        , 0.46516193, 0.        , 0.        ,
        0.46516193, 0.        , 0.        , 0.36673901, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.        , 0.        , 0.32555709, 0.        , 0.        ,
        0.       

In [16]:
query_embedding=vector.transform([preprocessed_query])

In [17]:
query_embedding.toarray()

array([[0.        , 0.        , 0.57735027, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.57735027, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.57735027, 0.        ,
        0.        , 0.        ]])

In [18]:
similarities = cosine_similarity(X, query_embedding)

In [19]:
similarities

array([[0.        ],
       [0.58300328],
       [0.        ],
       [0.56388142]])

In [22]:
ranked_documents = [documents[i] for i in ranked_indices]

In [23]:
ranked_indices=np.argsort(similarities, axis=0)[::-1].flatten()

In [24]:
ranked_indices

array([1, 3, 2, 0])

In [25]:
for i,doc in enumerate(ranked_documents):
  print(f"Rank {i+1}: {doc}")

Rank 1: Keywords are important for keyword-based search.
Rank 2: Keyword-based search relies on sparse embeddings.
Rank 3: Document analysis involves extracting keywords.
Rank 4: This is a list which containig sample documents.


In [27]:
query="Keyword-based search"

In [28]:
document_embeddings = np.array([
[0.634, 0.234, 0.867, 0.042, 0.249],
[0.123, 0.456, 0.789, 0.321, 0.654],
[0.987, 0.654, 0.321, 0.123, 0.456]])

In [29]:
query_embedding = np.array([[0.789, 0.321,0.654,0.987,0.123]])

In [30]:
similarities = cosine_similarity(document_embeddings, query_embedding)

In [31]:
ranked_indices=np.argsort(similarities, axis=0)[::-1].flatten()

In [32]:
ranked_indices=np.argsort(similarities, axis=0)[::-1].flatten()

In [33]:
ranked_indices

array([0, 2, 1])

In [34]:
for i,idx in enumerate(ranked_indices):
  print(f"Rank {i+1}: Document {idx+1}")

Rank 1: Document 1
Rank 2: Document 3
Rank 3: Document 2


In [1]:
doc_path = "/content/2005.11401v4.pdf"

In [2]:
!pip install pypdf langchain_community

In [3]:
from langchain_community.document_loaders import PyPDFLoader

In [4]:
loader=PyPDFLoader(doc_path)

In [5]:
docs=loader.load()

In [6]:
from langchain.text_splitter import RecursiveCharacterTextSplitter

In [7]:
splitter = RecursiveCharacterTextSplitter(chunk_size=200, chunk_overlap=30)

In [8]:
chunks = splitter.split_documents(docs)

In [9]:
chunks

[Document(metadata={'producer': 'pdfTeX-1.40.21', 'creator': 'LaTeX with hyperref', 'creationdate': '2021-04-13T00:48:38+00:00', 'author': '', 'keywords': '', 'moddate': '2021-04-13T00:48:38+00:00', 'ptex.fullbanner': 'This is pdfTeX, Version 3.14159265-2.6-1.40.21 (TeX Live 2020) kpathsea version 6.3.2', 'subject': '', 'title': '', 'trapped': '/False', 'source': '/content/2005.11401v4.pdf', 'total_pages': 19, 'page': 0, 'page_label': '1'}, page_content='Retrieval-Augmented Generation for\nKnowledge-Intensive NLP Tasks\nPatrick Lewis†‡, Ethan Perez⋆,\nAleksandra Piktus†, Fabio Petroni†, Vladimir Karpukhin†, Naman Goyal†, Heinrich Küttler†,'),
 Document(metadata={'producer': 'pdfTeX-1.40.21', 'creator': 'LaTeX with hyperref', 'creationdate': '2021-04-13T00:48:38+00:00', 'author': '', 'keywords': '', 'moddate': '2021-04-13T00:48:38+00:00', 'ptex.fullbanner': 'This is pdfTeX, Version 3.14159265-2.6-1.40.21 (TeX Live 2020) kpathsea version 6.3.2', 'subject': '', 'title': '', 'trapped': '/F

In [10]:
from langchain.embeddings import HuggingFaceInferenceAPIEmbeddings

In [11]:
from google.colab import userdata

HF_TOKEN=userdata.get("HF_TOKEN")

In [12]:
embeddings = HuggingFaceInferenceAPIEmbeddings(api_key=HF_TOKEN,model_name="BAAI/bge-base-en-v1.5")

In [22]:
!pip install chromadb

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.3/67.3 kB 3.6 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.3/18.3 MB 63.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 98.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 94.9/94.9 kB 12.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 284.2/284.2 kB 31.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 95.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.6/101.6 kB 14.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.0/16.0 MB 97.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.9/55.9 kB 7.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 92.0/92.0 kB 12.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.5/62.5 kB 7.6 MB/s eta 0:00:

In [13]:
from langchain.vectorstores import Chroma

In [14]:
vectorstore=Chroma.from_documents(chunks,embeddings)

In [15]:
vectorstore_retriever=vectorstore.as_retriever(search_kwargs={"k":3})

In [26]:
!pip install rank_bm25

In [16]:
from langchain.retrievers import BM25Retriever, EnsembleRetriever

In [17]:
keyword_retreiver = BM25Retriever.from_documents(chunks)

In [18]:
retreiver = EnsembleRetriever(retrievers=[vectorstore_retriever,keyword_retreiver],weights=[0.5,0.5])

In [19]:
model_name="HuggingFaceH4/zephyr-7b-beta"

In [31]:
!pip install -U bitsandbytes

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.1/76.1 MB 9.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 4.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 44.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 35.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 46.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 6.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 11.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 10.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 2.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 85.3 MB/s eta 0:00:00
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstallin

In [20]:
!pip install accelerate

In [21]:
import torch
from transformers import (AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig, pipeline)
from langchain import HuggingFacePipeline

In [22]:
def load_quantized_model(model_name: str):



  bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16,
  )

  model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype=torch.bfloat16,
    quantization_config=bnb_config,
  )

  return model

In [23]:
def initialize_tokenizer(model_name: str):
  tokenizer =AutoTokenizer.from_pretrained(model_name, return_token_type_ids=False)

  tokenizer.bos_token_id = 1

  return tokenizer

In [24]:
tokenizer=initialize_tokenizer(model_name)

tokenizer_config.json:   0%|          | 0.00/1.43k [00:00<?, ?B/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`


tokenizer.model:   0%|          | 0.00/493k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.80M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/42.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/168 [00:00<?, ?B/s]

In [25]:
model   =load_quantized_model(model_name)

config.json:   0%|          | 0.00/638 [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/23.9k [00:00<?, ?B/s]

Fetching 8 files:   0%|          | 0/8 [00:00<?, ?it/s]

Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`
Xet Storage is enabled for this repo, but the 'hf_xet' package is not in

model-00002-of-00008.safetensors:   0%|          | 0.00/1.95G [00:00<?, ?B/s]

model-00001-of-00008.safetensors:   0%|          | 0.00/1.89G [00:00<?, ?B/s]

model-00005-of-00008.safetensors:   0%|          | 0.00/1.98G [00:00<?, ?B/s]

model-00006-of-00008.safetensors:   0%|          | 0.00/1.95G [00:00<?, ?B/s]

model-00008-of-00008.safetensors:   0%|          | 0.00/816M [00:00<?, ?B/s]

model-00004-of-00008.safetensors:   0%|          | 0.00/1.95G [00:00<?, ?B/s]

model-00003-of-00008.safetensors:   0%|          | 0.00/1.98G [00:00<?, ?B/s]

model-00007-of-00008.safetensors:   0%|          | 0.00/1.98G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/8 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/111 [00:00<?, ?B/s]

In [26]:
pipeline = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,use_cache=True,device_map="auto",max_length=2048,do_sample=True,top_k=5,num_return_sequences=1,eos_token_id = tokenizer.eos_token_id, pad_token_id = tokenizer.pad_token_id
)


Device set to use cuda:0


In [27]:
llm=HuggingFacePipeline(pipeline=pipeline)

<ipython-input-27-2654db8a482e>:1: LangChainDeprecationWarning: The class `HuggingFacePipeline` was deprecated in LangChain 0.0.37 and will be removed in 1.0. An updated version of the class exists in the :class:`~langchain-huggingface package and should be used instead. To use it run `pip install -U :class:`~langchain-huggingface` and import as `from :class:`~langchain_huggingface import HuggingFacePipeline``.
  llm=HuggingFacePipeline(pipeline=pipeline)


In [28]:
from langchain.chains import RetrievalQA

In [29]:
normal_chain = RetrievalQA.from_chain_type(llm=llm,chain_type="stuff",retriever=vectorstore_retriever)

In [30]:
hybrid_chain = RetrievalQA.from_chain_type(llm=llm,chain_type="stuff",retriever=retreiver)

In [31]:
response1=normal_chain.invoke("What is RAG token model?")

Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


In [32]:
print(response1["result"])

Use the following pieces of context to answer the question at the end. If you don't know the answer, just say that you don't know, don't try to make up an answer.

RAG-Token The RAG-Token model can be seen as a standard, autoregressive seq2seq genera-
tor with transition probability: p′
θ(yi|x,y1:i−1) = ∑
z∈top-k(p(·|x)) pη(zi|x)pθ(yi|x,zi,y1:i−1) To

distribution over generated text. In one approach, RAG-Sequence, the model uses the same document
to predict each target token. The second approach, RAG-Token, can predict each target token based

2.1 Models
RAG-Sequence Model The RAG-Sequence model uses the same retrieved document to generate
the complete sequence. Technically, it treats the retrieved document as a single latent variable that

Question: What is RAG token model?
Helpful Answer: RAG-Token is a model in natural language generation that predicts each target token based on the context of the text rather than using the same retrieved document to predict all target tokens, as i

In [33]:

response2=hybrid_chain.invoke("What is RAG token model?")

In [34]:
response2

{'query': 'What is RAG token model?',
 'result': "Use the following pieces of context to answer the question at the end. If you don't know the answer, just say that you don't know, don't try to make up an answer.\n\nRAG-Token The RAG-Token model can be seen as a standard, autoregressive seq2seq genera-\ntor with transition probability: p′\nθ(yi|x,y1:i−1) = ∑\nz∈top-k(p(·|x)) pη(zi|x)pθ(yi|x,zi,y1:i−1) To\n\nSun Also Rises”. Similarly, document 1 dominates the posterior when “A Farewell to Arms” is\ngenerated. Intriguingly, after the first token of each book is generated, the document posterior flattens.\n\ndistribution over generated text. In one approach, RAG-Sequence, the model uses the same document\nto predict each target token. The second approach, RAG-Token, can predict each target token based\n\nthe parameters of a language model? arXiv e-prints, 2020. URL https://arxiv.org/abs/\n2002.08910.\n[53] Stephen Robertson and Hugo Zaragoza. The probabilistic relevance framework: Bm25 and

In [35]:
print(response2["result"])

Use the following pieces of context to answer the question at the end. If you don't know the answer, just say that you don't know, don't try to make up an answer.

RAG-Token The RAG-Token model can be seen as a standard, autoregressive seq2seq genera-
tor with transition probability: p′
θ(yi|x,y1:i−1) = ∑
z∈top-k(p(·|x)) pη(zi|x)pθ(yi|x,zi,y1:i−1) To

Sun Also Rises”. Similarly, document 1 dominates the posterior when “A Farewell to Arms” is
generated. Intriguingly, after the first token of each book is generated, the document posterior flattens.

distribution over generated text. In one approach, RAG-Sequence, the model uses the same document
to predict each target token. The second approach, RAG-Token, can predict each target token based

the parameters of a language model? arXiv e-prints, 2020. URL https://arxiv.org/abs/
2002.08910.
[53] Stephen Robertson and Hugo Zaragoza. The probabilistic relevance framework: Bm25 and

2.1 Models
RAG-Sequence Model The RAG-Sequence model uses the s

#Reranking

In [36]:
!pip install cohere

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 259.5/259.5 kB 4.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 57.1 MB/s eta 0:00:00


In [37]:
COHERE_API = userdata.get("COHERE_API")

In [41]:
from langchain.retrievers import ContextualCompressionRetriever
from langchain.retrievers.document_compressors import CohereRerank

In [42]:
compressor = CohereRerank(cohere_api_key=COHERE_API)

<ipython-input-42-24dd67765ee7>:1: LangChainDeprecationWarning: The class `CohereRerank` was deprecated in LangChain 0.0.30 and will be removed in 1.0. An updated version of the class exists in the :class:`~langchain-cohere package and should be used instead. To use it run `pip install -U :class:`~langchain-cohere` and import as `from :class:`~langchain_cohere import CohereRerank``.
  compressor = CohereRerank(cohere_api_key=COHERE_API)


In [45]:
compression_retriever = ContextualCompressionRetriever(
    base_compressor=compressor, base_retriever=retreiver
    )

In [48]:
compressed_docs = compression_retriever.get_relevant_documents("What is RAG token model?")

<ipython-input-48-2e8499c6cf5a>:1: LangChainDeprecationWarning: The method `BaseRetriever.get_relevant_documents` was deprecated in langchain-core 0.1.46 and will be removed in 1.0. Use :meth:`~invoke` instead.
  compressed_docs = compression_retriever.get_relevant_documents("What is RAG token model?")


In [49]:
hybrid_chain = RetrievalQA.from_chain_type(
    llm=llm, chain_type="stuff", retriever=compression_retriever
)

In [50]:
response = hybrid_chain.invoke("What is RAG token model?")

In [53]:
response

{'query': 'What is RAG token model?',
 'result': "Use the following pieces of context to answer the question at the end. If you don't know the answer, just say that you don't know, don't try to make up an answer.\n\nRAG-Token The RAG-Token model can be seen as a standard, autoregressive seq2seq genera-\ntor with transition probability: p′\nθ(yi|x,y1:i−1) = ∑\nz∈top-k(p(·|x)) pη(zi|x)pθ(yi|x,zi,y1:i−1) To\n\ndistribution over generated text. In one approach, RAG-Sequence, the model uses the same document\nto predict each target token. The second approach, RAG-Token, can predict each target token based\n\n2.1 Models\nRAG-Sequence Model The RAG-Sequence model uses the same retrieved document to generate\nthe complete sequence. Technically, it treats the retrieved document as a single latent variable that\n\nQuestion: What is RAG token model?\nHelpful Answer: The RAG token model is a variant of the standard autoregressive seq2seq generator, with an added transition probability that uses a 

In [52]:
print(response["result"])

Use the following pieces of context to answer the question at the end. If you don't know the answer, just say that you don't know, don't try to make up an answer.

RAG-Token The RAG-Token model can be seen as a standard, autoregressive seq2seq genera-
tor with transition probability: p′
θ(yi|x,y1:i−1) = ∑
z∈top-k(p(·|x)) pη(zi|x)pθ(yi|x,zi,y1:i−1) To

distribution over generated text. In one approach, RAG-Sequence, the model uses the same document
to predict each target token. The second approach, RAG-Token, can predict each target token based

2.1 Models
RAG-Sequence Model The RAG-Sequence model uses the same retrieved document to generate
the complete sequence. Technically, it treats the retrieved document as a single latent variable that

Question: What is RAG token model?
Helpful Answer: The RAG token model is a variant of the standard autoregressive seq2seq generator, with an added transition probability that uses a distribution over generated text instead of just predicting each 